//! Helpers for recording workspace file writes in the active tool context.
//!
//! Mirrors the Python `opensquilla.tools.write_tracking` module: classifies
//! workspace-relative paths (source / test-like / generated / docs / scratch),
//! records file reads/writes in the context ledger, snapshots and diffs git
//! mutation state, and produces hygiene notes for risky write targets.

use crate::context::ToolContext;
use crate::policy_config::fnmatchcase;
use crate::registry::ToolError;
use regex::Regex;
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

const GENERATED_OR_DERIVED_PATH_PATTERNS: &[&str] = &[
    "*.prebuilt",
    "*.generated.*",
    "*.min.*",
    "*.bundle.*",
    "dist/**",
    "build/**",
    "target/**",
    "generated/**",
    "gen/**",
];

const DOCUMENTATION_PATH_PATTERNS: &[&str] = &[
    "docs/**",
    "doc/**",
    "documentation/**",
    "manual/**",
    "**/manual/**",
];

const TEST_PATH_PATTERNS: &[&str] = &[
    "test/**",
    "tests/**",
    "__tests__/**",
    "**/__tests__/**",
    "*.spec.*",
    "*.test.*",
    "**/*.spec.*",
    "**/*.test.*",
];

const GENERATED_CONTENT_MARKERS: &[&str] = &[
    "a bison parser, made by gnu bison",
    "code generated",
    "automatically generated",
    "auto-generated",
    "do not edit",
    "do not modify",
    "generated by",
    "this file was generated",
];

fn test_path_regexes() -> &'static [Regex] {
    static RE: std::sync::LazyLock<Vec<Regex>> = std::sync::LazyLock::new(|| {
        vec![
            Regex::new(r"(?i)(^|/)test_[^/]+\.[^/]+$").expect("test regex 1"),
            Regex::new(r"(?i)(^|/)[^/]+_test\.[^/]+$").expect("test regex 2"),
            Regex::new(r"(?i)(^|/)[^/]*test[^/]*\.(py|js|ts|tsx|rb|php|sh|txt|java|go|zsh)$")
                .expect("test regex 3"),
        ]
    });
    &RE
}

fn scratch_artifact_path_regexes() -> &'static [Regex] {
    static RE: std::sync::LazyLock<Vec<Regex>> = std::sync::LazyLock::new(|| {
        vec![
            Regex::new(r"(?i)(^|/)(tmp|temp|scratch)(/|$)").expect("scratch regex 1"),
            Regex::new(r"(?i)(^|/)\.?(pytest_cache|mypy_cache|ruff_cache|phpunit\.cache)(/|$)")
                .expect("scratch regex 2"),
            Regex::new(r"(?i)^[^/]*(debug|repro|reproduce|scratch|verify|inspect|investigate)[^/]*\.(py|js|ts|rb|php|sh|txt|md|json|yaml|yml|patch|diff|zsh)$")
                .expect("scratch regex 3"),
            Regex::new(r"(?i)^[^/]*(debug|repro|reproduce|scratch)[^/]*/").expect("scratch regex 4"),
            Regex::new(r"(?i)(^|/)[^/]*\.(patch|diff)$").expect("scratch regex 5"),
        ]
    });
    &RE
}

const SCRATCH_ONLY_NUDGE_COUNTS: &[u32] = &[3, 6, 10];
const WORKSPACE_WRITE_PROGRESS_COUNTS: &[u32] = &[1, 3, 6, 10];

/// Normalize a workspace-relative path spelling.
pub fn normalize_relative_path(path: &str) -> String {
    let mut normalized = path.replace('\\', "/");
    while normalized.starts_with("./") {
        normalized = normalized[2..].to_string();
    }
    normalized.trim_start_matches('/').to_string()
}

fn matches_any(path: &str, patterns: &[&str]) -> bool {
    patterns.iter().any(|pattern| fnmatchcase(pattern, path))
}

fn looks_test_file(normalized: &str) -> bool {
    matches_any(normalized, TEST_PATH_PATTERNS)
        || test_path_regexes().iter().any(|re| re.is_match(normalized))
}

fn looks_scratch_artifact_path(normalized: &str) -> bool {
    scratch_artifact_path_regexes()
        .iter()
        .any(|re| re.is_match(normalized))
}

fn has_generated_content_marker(path: &Path) -> bool {
    let Ok(bytes) = std::fs::read(path) else {
        return false;
    };
    if !path.is_file() {
        return false;
    }
    let sample = String::from_utf8_lossy(&bytes[..bytes.len().min(4096)]).to_ascii_lowercase();
    GENERATED_CONTENT_MARKERS
        .iter()
        .any(|marker| sample.contains(marker))
}

fn looks_generated_or_derived(path: &Path, normalized: &str) -> bool {
    matches_any(normalized, GENERATED_OR_DERIVED_PATH_PATTERNS)
        || has_generated_content_marker(path)
}

fn path_is_inside_scratch(normalized: &str, ctx: &ToolContext) -> bool {
    let (Some(workspace), Some(scratch)) = (&ctx.workspace_dir, &ctx.scratch_dir) else {
        return false;
    };
    let scratch_relative = scratch
        .strip_prefix(workspace)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .unwrap_or_default();
    if scratch_relative.is_empty() {
        return false;
    }
    normalized == scratch_relative || normalized.starts_with(&format!("{scratch_relative}/"))
}

/// Classify a workspace-relative path into a stability bucket.
pub fn classify_workspace_path(relative_path: &str, ctx: &ToolContext) -> &'static str {
    let normalized = normalize_relative_path(relative_path);
    if path_is_inside_scratch(&normalized, ctx) {
        return "scratch";
    }
    if looks_test_file(&normalized) {
        return "test-like";
    }
    if looks_scratch_artifact_path(&normalized) {
        return "scratch";
    }
    if matches_any(&normalized, DOCUMENTATION_PATH_PATTERNS) {
        return "docs";
    }
    let path = Path::new(&normalized);
    if looks_generated_or_derived(path, &normalized) {
        return "generated";
    }
    if !normalized.is_empty() {
        return "source";
    }
    "unknown"
}

/// SHA-256 hex digest of ledger hint text.
pub fn mutation_ledger_text_hash(text: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(text.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// A file fingerprint for fresh-read guarding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileFingerprint {
    pub size: u64,
    pub mtime_ns: i64,
    pub sha256: String,
}

/// Fingerprint a file (size, mtime, sha256). Fails for missing/unreadable
/// files or directories.
pub fn fingerprint_file(path: &Path) -> Result<FileFingerprint, ToolError> {
    let stat = std::fs::metadata(path)
        .map_err(|_| ToolError::new("FINGERPRINT", format!("cannot stat {}", path.display())))?;
    if !stat.is_file() {
        return Err(ToolError::new(
            "FINGERPRINT",
            format!("not a file: {}", path.display()),
        ));
    }
    let mut hasher = Sha256::new();
    let bytes = std::fs::read(path)
        .map_err(|_| ToolError::new("FINGERPRINT", format!("cannot read {}", path.display())))?;
    hasher.update(&bytes);
    let mtime_ns = stat
        .modified()
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_nanos() as i64)
        .unwrap_or(0);
    Ok(FileFingerprint {
        size: bytes.len() as u64,
        mtime_ns,
        sha256: format!("{:x}", hasher.finalize()),
    })
}

/// Resolve a path for workspace-relative computation without requiring the
/// path to exist (`resolve(strict=False)` equivalent).
fn loose_resolve(path: &Path) -> PathBuf {
    if let Ok(canonical) = path.canonicalize() {
        return canonical;
    }
    // On Windows a root-relative path (`/foo`) has a root but `is_absolute()`
    // is false; keep it root-relative rather than joining the current dir.
    let rooted = if path.is_absolute() || path.has_root() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .map(|cwd| cwd.join(path))
            .unwrap_or_else(|_| path.to_path_buf())
    };
    normalize_lexical(&rooted)
}

/// Resolve a context's workspace root with `resolve(strict=False)` semantics.
fn resolved_workspace_root(ctx: &ToolContext) -> Option<PathBuf> {
    ctx.workspace_dir.as_ref().map(|p| loose_resolve(p))
}

fn normalize_lexical(path: &Path) -> PathBuf {
    let mut components: Vec<std::path::Component> = Vec::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                if matches!(components.last(), Some(std::path::Component::Normal(_))) {
                    components.pop();
                } else if !matches!(components.last(), Some(std::path::Component::RootDir)) {
                    components.push(component);
                }
            }
            other => components.push(other),
        }
    }
    components.iter().collect()
}

/// Record a workspace file write in the context ledger.
pub fn record_workspace_file_write(
    ctx: &mut ToolContext,
    path: &Path,
    operation: &str,
    created: bool,
) {
    let Some(workspace) = resolved_workspace_root(ctx) else {
        return;
    };
    let resolved = loose_resolve(path);
    let Ok(relative_path) = resolved.strip_prefix(&workspace) else {
        return;
    };
    ctx.workspace_file_writes.push(json!({
        "path": resolved.to_string_lossy(),
        "relative_path": relative_path.to_string_lossy().replace('\\', "/"),
        "name": path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
        "suffix": path.extension().map(|e| e.to_string_lossy().to_ascii_lowercase()).unwrap_or_default(),
        "operation": operation,
        "created": created,
    }));
}

/// Record a workspace file read in the context ledger.
pub fn record_workspace_file_read(
    ctx: &mut ToolContext,
    path: &Path,
    operation: &str,
    offset: Option<u64>,
    limit: Option<u64>,
    complete: Option<bool>,
) {
    let Some(workspace) = resolved_workspace_root(ctx) else {
        return;
    };
    let resolved = loose_resolve(path);
    let Ok(relative_path) = resolved.strip_prefix(&workspace) else {
        return;
    };
    let mut read_record = serde_json::Map::new();
    read_record.insert("path".into(), json!(resolved.to_string_lossy()));
    read_record.insert(
        "relative_path".into(),
        json!(relative_path.to_string_lossy().replace('\\', "/")),
    );
    read_record.insert(
        "name".into(),
        json!(
            path.file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default()
        ),
    );
    read_record.insert(
        "suffix".into(),
        json!(
            path.extension()
                .map(|e| e.to_string_lossy().to_ascii_lowercase())
                .unwrap_or_default()
        ),
    );
    read_record.insert("operation".into(), json!(operation));
    if let Some(offset) = offset {
        read_record.insert("offset".into(), json!(offset));
    }
    if let Some(limit) = limit {
        read_record.insert("limit".into(), json!(limit));
    }
    if let Some(complete) = complete {
        read_record.insert("complete".into(), json!(complete));
        let key = resolved.to_string_lossy().to_string();
        if let Ok(fp) = fingerprint_file(&resolved) {
            let mut state = serde_json::Map::new();
            state.insert("path".into(), json!(resolved.to_string_lossy()));
            state.insert(
                "relative_path".into(),
                json!(relative_path.to_string_lossy().replace('\\', "/")),
            );
            state.insert("operation".into(), json!(operation));
            state.insert("size".into(), json!(fp.size));
            state.insert("mtime_ns".into(), json!(fp.mtime_ns));
            state.insert("sha256".into(), json!(fp.sha256));
            ctx.workspace_file_read_state
                .insert(key, Value::Object(state));
        }
    }
    ctx.workspace_file_reads.push(Value::Object(read_record));
}

/// Require a fresh full-file read of a workspace path before an edit.
///
/// Mirrors `require_fresh_workspace_file_read`: when the context's
/// `file_edit_requires_fresh_read` lever is set and the target is an existing
/// workspace file that was never fully read (or whose fingerprint changed),
/// returns a retryable `ToolError`.
pub fn require_fresh_workspace_file_read(
    ctx: &ToolContext,
    path: &Path,
    tool_name: &str,
    original_path: &str,
) -> Result<(), ToolError> {
    if ctx.full_host_access_active() {
        return Ok(());
    }
    if !ctx.file_edit_requires_fresh_read {
        return Ok(());
    }
    let Some(workspace) = resolved_workspace_root(ctx) else {
        return Ok(());
    };
    let resolved = loose_resolve(path);
    if resolved.strip_prefix(&workspace).is_err() {
        return Ok(());
    }
    if let Some(scratch) = &ctx.scratch_dir {
        if resolved.strip_prefix(scratch).is_ok() {
            return Ok(());
        }
    }
    if !resolved.exists() {
        return Ok(());
    }

    let key = resolved.to_string_lossy().to_string();
    let Some(state) = ctx.workspace_file_read_state.get(&key) else {
        let action = if tool_name == "edit_file" {
            "edit"
        } else {
            "write"
        };
        return Err(ToolError::new(
            "FRESH_READ_REQUIRED",
            format!(
                "{tool_name} must read existing workspace file before modifying it: \
                 {original_path}. Use read_file without offset or limit, then retry the {action}."
            ),
        ));
    };
    let Ok(current) = fingerprint_file(&resolved) else {
        return Err(ToolError::new(
            "FRESH_READ_REQUIRED",
            format!(
                "{tool_name} could not verify the current file before modifying it: \
                 {original_path}. Use read_file without offset or limit, then retry."
            ),
        ));
    };
    let state_size = state.get("size").and_then(|v| v.as_u64());
    let state_sha = state.get("sha256").and_then(|v| v.as_str());
    if state_size != Some(current.size) || state_sha != Some(current.sha256.as_str()) {
        return Err(ToolError::new(
            "FRESH_READ_REQUIRED",
            format!(
                "{original_path} changed since it was read. Use read_file without offset \
                 or limit to refresh context, then retry {tool_name}."
            ),
        ));
    }
    Ok(())
}

/// Record a scratch file write in the context ledger.
pub fn record_scratch_file_write(ctx: &mut ToolContext, path: &Path) {
    let Some(scratch) = ctx.scratch_dir.as_ref().map(|p| loose_resolve(p)) else {
        return;
    };
    let resolved = loose_resolve(path);
    let Ok(relative_path) = resolved.strip_prefix(&scratch) else {
        return;
    };
    ctx.scratch_file_writes.push(json!({
        "path": resolved.to_string_lossy(),
        "relative_path": relative_path.to_string_lossy().replace('\\', "/"),
        "name": path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
        "suffix": path.extension().map(|e| e.to_string_lossy().to_ascii_lowercase()).unwrap_or_default(),
    }));
}

fn is_nudge_count(count: usize, triggers: &[u32]) -> bool {
    triggers.contains(&(count as u32)) || (count != 0 && count % 10 == 0)
}

/// Return a compact progress nudge after repeated scratch-only writes.
pub fn scratch_only_progress_note(ctx: &ToolContext) -> String {
    let scratch_writes = ctx.scratch_file_writes.len();
    if !is_nudge_count(scratch_writes, SCRATCH_ONLY_NUDGE_COUNTS) {
        return String::new();
    }
    let workspace_writes = ctx.workspace_file_writes.len();
    if workspace_writes != 0 {
        return String::new();
    }
    format!(
        " Note: this turn has written {scratch_writes} scratch file(s) and no real \
         workspace file changes yet. Scratch files are temporary; if the task requires \
         changing the project, use the scratch findings to edit the actual workspace \
         file(s) before final."
    )
}

/// Return a compact progress note when workspace writes are present.
pub fn workspace_write_progress_note(ctx: &ToolContext) -> String {
    let workspace_writes = ctx.workspace_file_writes.len();
    if !is_nudge_count(workspace_writes, WORKSPACE_WRITE_PROGRESS_COUNTS) {
        return String::new();
    }
    " Note: workspace changes are now present. Before final, inspect git_diff \
     and run focused verification for the changed behavior."
        .to_string()
}

fn workspace_relative_path(ctx: &ToolContext, path: &Path) -> Option<String> {
    let workspace = resolved_workspace_root(ctx)?;
    let resolved = loose_resolve(path);
    resolved
        .strip_prefix(&workspace)
        .ok()
        .map(|p| p.to_string_lossy().replace('\\', "/"))
}

/// Return a short hygiene note for risky workspace write targets.
pub fn workspace_write_note(ctx: &ToolContext, path: &Path) -> String {
    let Some(relative_path) = workspace_relative_path(ctx, path) else {
        return String::new();
    };
    let normalized = normalize_relative_path(&relative_path);
    let path = Path::new(&normalized);
    let mut notes: Vec<&str> = Vec::new();
    if looks_generated_or_derived(path, &normalized) {
        notes.push(
            "generated or derived-looking file; confirm it is a source of truth or \
             regenerate/verify or remove it before final",
        );
    }
    if matches_any(&normalized, DOCUMENTATION_PATH_PATTERNS) {
        notes.push("documentation file; verify the docs build if retaining this change");
    }
    if looks_test_file(&normalized) {
        notes.push(
            "test file; only retain this change if the user explicitly requested test \
             updates, otherwise move the fix to source files or revert it before final",
        );
    }
    if notes.is_empty() {
        String::new()
    } else {
        format!(" (note: {})", notes.join("; "))
    }
}

/// Return one compact note covering a set of workspace write targets.
pub fn summarize_workspace_write_notes(ctx: &ToolContext, paths: &[&Path]) -> String {
    let mut saw_generated = false;
    let mut saw_docs = false;
    let mut saw_tests = false;
    for path in paths {
        let Some(relative_path) = workspace_relative_path(ctx, path) else {
            continue;
        };
        let normalized = normalize_relative_path(&relative_path);
        let p = Path::new(&normalized);
        saw_generated |= looks_generated_or_derived(p, &normalized);
        saw_docs |= matches_any(&normalized, DOCUMENTATION_PATH_PATTERNS);
        saw_tests |= looks_test_file(&normalized);
    }
    let mut notes: Vec<String> = Vec::new();
    if saw_generated {
        notes.push(
            "generated or derived-looking file(s) changed; confirm they are sources of \
             truth or regenerate/verify or remove them before final"
                .to_string(),
        );
    }
    if saw_docs {
        notes.push(
            "documentation file(s) changed; verify the docs build if retaining them".to_string(),
        );
    }
    if saw_tests {
        notes.push(
            "test file(s) changed; only retain them if the user explicitly requested test \
             updates, otherwise move the fix to source files or revert them before final"
                .to_string(),
        );
    }
    if notes.is_empty() {
        String::new()
    } else {
        format!(" Note: {}.", notes.join("; "))
    }
}

/// Return an explicit final-diff warning for likely risky changed paths.
pub fn summarize_patch_hygiene_warning(ctx: &ToolContext, paths: &[&Path]) -> String {
    let mut saw_generated = false;
    let mut saw_docs = false;
    let mut saw_tests = false;
    for path in paths {
        let Some(relative_path) = workspace_relative_path(ctx, path) else {
            continue;
        };
        let normalized = normalize_relative_path(&relative_path);
        let p = Path::new(&normalized);
        saw_generated |= looks_generated_or_derived(p, &normalized);
        saw_docs |= matches_any(&normalized, DOCUMENTATION_PATH_PATTERNS);
        saw_tests |= looks_test_file(&normalized);
    }
    let mut notes: Vec<String> = Vec::new();
    if saw_generated {
        notes.push(
            "generated or derived-looking file(s) are present in the final diff; unless \
             those are intentional source-of-truth changes, remove them before final"
                .to_string(),
        );
    }
    if saw_docs {
        notes.push(
            "documentation file(s) are present in the final diff; verify the docs build \
             from a clean checkout, and remove them if the task does not require docs \
             changes; timestamp-only workarounds do not travel with the final patch"
                .to_string(),
        );
    }
    if saw_tests {
        notes.push(
            "test file(s) are present in the final diff; if the user did not explicitly \
             ask for test updates, revert them and put the functional change in source files"
                .to_string(),
        );
    }
    if notes.is_empty() {
        String::new()
    } else {
        format!("[patch_hygiene_warning] {}.", notes.join("; "))
    }
}

/// Snapshot workspace git mutation state as a `relative_path -> status` map.
pub fn snapshot_workspace_mutations(workspace: &Path) -> BTreeMap<String, String> {
    let Ok(output) = std::process::Command::new("git")
        .args(["status", "--porcelain=v1", "-z", "--untracked-files=all"])
        .current_dir(workspace)
        .output()
    else {
        return BTreeMap::new();
    };
    if !output.status.success() {
        return BTreeMap::new();
    }
    parse_git_status_z(&String::from_utf8_lossy(&output.stdout))
}

/// Parse `git status --porcelain -z` output into `relative_path -> status`.
pub fn parse_git_status_z(output: &str) -> BTreeMap<String, String> {
    let mut records = BTreeMap::new();
    let entries: Vec<&str> = output.split('\0').collect();
    let mut index = 0;
    while index < entries.len() {
        let entry = entries[index];
        index += 1;
        if entry.is_empty() {
            continue;
        }
        let status = &entry[..entry.len().min(2)];
        let mut relative_path = if entry.len() > 3 { &entry[3..] } else { "" };
        if relative_path.is_empty() {
            continue;
        }
        if matches!(status.as_bytes().first(), Some(b'R') | Some(b'C')) && index < entries.len() {
            relative_path = entries[index];
            index += 1;
        }
        records.insert(relative_path.replace('\\', "/"), status.to_string());
    }
    records
}

/// Diff two workspace mutation snapshots into per-path change entries.
pub fn diff_workspace_mutations(
    before: &BTreeMap<String, String>,
    after: &BTreeMap<String, String>,
    ctx: &ToolContext,
) -> Vec<Value> {
    let mut keys: Vec<&String> = before.keys().chain(after.keys()).collect();
    keys.sort();
    keys.dedup();
    let mut entries = Vec::new();
    for relative_path in keys {
        let before_status = before.get(relative_path);
        let after_status = after.get(relative_path);
        if before_status == after_status {
            continue;
        }
        entries.push(json!({
            "relative_path": relative_path,
            "status": after_status.cloned().unwrap_or_else(|| "deleted".to_string()),
            "classification": classify_workspace_path(relative_path, ctx),
        }));
    }
    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn workspace_ctx() -> ToolContext {
        ToolContext {
            workspace_dir: Some(PathBuf::from("/workspace")),
            ..Default::default()
        }
    }

    #[test]
    fn classifies_source_paths() {
        let ctx = workspace_ctx();
        assert_eq!(classify_workspace_path("src/main.rs", &ctx), "source");
        assert_eq!(classify_workspace_path("lib/foo.py", &ctx), "source");
    }

    #[test]
    fn classifies_test_paths() {
        let ctx = workspace_ctx();
        assert_eq!(
            classify_workspace_path("tests/test_foo.py", &ctx),
            "test-like"
        );
        assert_eq!(
            classify_workspace_path("src/foo.test.ts", &ctx),
            "test-like"
        );
        assert_eq!(
            classify_workspace_path("src/foo_spec_test.go", &ctx),
            "test-like"
        );
    }

    #[test]
    fn classifies_generated_and_docs() {
        let ctx = workspace_ctx();
        assert_eq!(classify_workspace_path("dist/bundle.js", &ctx), "generated");
        assert_eq!(classify_workspace_path("target/debug/x", &ctx), "generated");
        assert_eq!(classify_workspace_path("docs/readme.md", &ctx), "docs");
        assert_eq!(classify_workspace_path("manual/guide.txt", &ctx), "docs");
    }

    #[test]
    fn classifies_scratch_paths() {
        let ctx = workspace_ctx();
        assert_eq!(classify_workspace_path("tmp/x.py", &ctx), "scratch");
        assert_eq!(classify_workspace_path("debug_x.py", &ctx), "scratch");
        assert_eq!(classify_workspace_path("patch.diff", &ctx), "scratch");
    }

    #[test]
    fn classifies_inside_scratch_dir() {
        let ctx = ToolContext {
            workspace_dir: Some(PathBuf::from("/workspace")),
            scratch_dir: Some(PathBuf::from("/workspace/.scratch")),
            ..Default::default()
        };
        assert_eq!(
            classify_workspace_path(".scratch/repro.py", &ctx),
            "scratch"
        );
    }

    #[test]
    fn normalizes_relative_paths() {
        assert_eq!(normalize_relative_path("./src/x.rs"), "src/x.rs");
        assert_eq!(normalize_relative_path("/src/x.rs"), "src/x.rs");
        assert_eq!(normalize_relative_path("a\\b\\c.rs"), "a/b/c.rs");
    }

    #[test]
    fn mutation_ledger_hash_is_sha256() {
        let hash = mutation_ledger_text_hash("hello");
        assert_eq!(hash.len(), 64);
        assert_eq!(mutation_ledger_text_hash("hello"), hash);
    }

    #[test]
    fn parse_git_status_z_handles_renames() {
        let output = " M src/a.rs\0?? new_file.py\0R  old.rs\0new.rs\0";
        let parsed = parse_git_status_z(output);
        assert_eq!(parsed.get("src/a.rs").map(|s| s.as_str()), Some(" M"));
        assert_eq!(parsed.get("new_file.py").map(|s| s.as_str()), Some("??"));
        assert_eq!(parsed.get("new.rs").map(|s| s.as_str()), Some("R "));
        assert!(parsed.get("old.rs").is_none());
    }

    #[test]
    fn diff_workspace_mutations_detects_changes() {
        let before: BTreeMap<String, String> = BTreeMap::new();
        let mut after = BTreeMap::new();
        after.insert("src/a.rs".to_string(), " M".to_string());
        after.insert("new.py".to_string(), "??".to_string());
        let ctx = workspace_ctx();
        let diff = diff_workspace_mutations(&before, &after, &ctx);
        assert_eq!(diff.len(), 2);
        assert_eq!(diff[0]["relative_path"], "new.py");
        assert_eq!(diff[1]["relative_path"], "src/a.rs");
        assert_eq!(diff[1]["classification"], "source");
    }

    #[test]
    fn progress_notes_fire_at_thresholds() {
        let mut ctx = workspace_ctx();
        assert_eq!(scratch_only_progress_note(&ctx), "");
        for _ in 0..3 {
            ctx.scratch_file_writes.push(json!({}));
        }
        assert!(scratch_only_progress_note(&ctx).contains("scratch file(s)"));

        let mut ctx2 = workspace_ctx();
        for _ in 0..3 {
            ctx2.workspace_file_writes.push(json!({}));
        }
        assert!(workspace_write_progress_note(&ctx2).contains("workspace changes"));
    }

    #[test]
    fn workspace_write_note_flags_tests() {
        let ctx = workspace_ctx();
        let note = workspace_write_note(&ctx, Path::new("/workspace/tests/x.py"));
        assert!(note.contains("test file"));
    }

    #[test]
    fn fingerprint_matches() {
        let temp = tempfile::NamedTempFile::new().expect("temp");
        std::fs::write(temp.path(), b"hello").expect("write");
        let fp = fingerprint_file(temp.path()).expect("fingerprint");
        assert_eq!(fp.size, 5);
        assert_eq!(fp.sha256.len(), 64);
    }

    #[test]
    fn fresh_read_guard_requires_prior_read() {
        let mut ctx = workspace_ctx();
        ctx.file_edit_requires_fresh_read = true;
        let temp = tempfile::NamedTempFile::new().expect("temp");
        let result = require_fresh_workspace_file_read(&ctx, temp.path(), "edit_file", "the file");
        // Temp file is outside the workspace, so the guard is skipped.
        assert!(result.is_ok());

        // With a workspace, the guard triggers when no read is recorded.
        let wspace = tempfile::tempdir().expect("wspace");
        let workspace = wspace.path().canonicalize().expect("canonical workspace");
        let file = workspace.join("x.txt");
        std::fs::write(&file, b"hello").expect("write");
        let mut ctx = ToolContext {
            workspace_dir: Some(workspace.clone()),
            file_edit_requires_fresh_read: true,
            ..Default::default()
        };
        assert!(require_fresh_workspace_file_read(&ctx, &file, "edit_file", "x.txt").is_err());

        // Recording a complete read makes the guard pass.
        record_workspace_file_read(&mut ctx, &file, "read", None, None, Some(true));
        assert!(require_fresh_workspace_file_read(&ctx, &file, "edit_file", "x.txt").is_ok());
    }
}
