//! Syscall name → number resolution.
//!
//! On Linux we defer to `libc::SYS_*` constants at compile time so the table
//! is always correct for the target architecture. On non-Linux platforms we
//! provide static x86_64 numbers so the filter can still be built (e.g. for
//! tests or cross-compilation), though it would only be installable on Linux.
//!
//! The table is intentionally large: the seccomp builder looks up names here
//! and an unknown name should be a hard error, not a silent skip.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Resolve a syscall name to its number, if known.
///
/// On Linux this consults `libc::SYS_*` for the target architecture. On
/// non-Linux it falls back to a static x86_64 table.
pub fn syscall_name_to_number(name: &str) -> Option<i64> {
    #[cfg(target_os = "linux")]
    {
        linux_lookup(name)
    }
    #[cfg(not(target_os = "linux"))]
    {
        fallback_x86_64_lookup(name)
    }
}

/// A static list of `(name, number)` pairs used both for the fallback table on
/// non-Linux and for documentation. The numbers are x86_64.
pub static SYSCALL_NAMES: &[(&str, i64)] = &[
    // ---- Process / thread management ----
    ("read", 0),
    ("write", 1),
    ("open", 2),
    ("close", 3),
    ("stat", 4),
    ("fstat", 5),
    ("lstat", 6),
    ("poll", 7),
    ("lseek", 8),
    ("mmap", 9),
    ("mprotect", 10),
    ("munmap", 11),
    ("brk", 12),
    ("rt_sigaction", 13),
    ("rt_sigprocmask", 14),
    ("rt_sigreturn", 15),
    ("ioctl", 16),
    ("pread64", 17),
    ("pwrite64", 18),
    ("readv", 19),
    ("writev", 20),
    ("access", 21),
    ("pipe", 22),
    ("select", 23),
    ("sched_yield", 24),
    ("mremap", 25),
    ("msync", 26),
    ("mincore", 27),
    ("madvise", 28),
    ("shmget", 29),
    ("shmat", 30),
    ("shmctl", 31),
    ("dup", 32),
    ("dup2", 33),
    ("pause", 34),
    ("nanosleep", 35),
    ("getitimer", 36),
    ("alarm", 37),
    ("setitimer", 38),
    ("getpid", 39),
    ("sendfile", 40),
    ("socket", 41),
    ("connect", 42),
    ("accept", 43),
    ("sendto", 44),
    ("recvfrom", 45),
    ("sendmsg", 46),
    ("recvmsg", 47),
    ("shutdown", 48),
    ("bind", 49),
    ("listen", 50),
    ("getsockname", 51),
    ("getpeername", 52),
    ("socketpair", 53),
    ("setsockopt", 54),
    ("getsockopt", 55),
    ("clone", 56),
    ("fork", 57),
    ("vfork", 58),
    ("execve", 59),
    ("exit", 60),
    ("wait4", 61),
    ("kill", 62),
    ("uname", 63),
    ("semget", 64),
    ("semop", 65),
    ("semctl", 66),
    ("shmdt", 67),
    ("msgget", 68),
    ("msgsnd", 69),
    ("msgrcv", 70),
    ("msgctl", 71),
    ("fcntl", 72),
    ("flock", 73),
    ("fsync", 74),
    ("fdatasync", 75),
    ("truncate", 76),
    ("ftruncate", 77),
    ("getdents", 78),
    ("getcwd", 79),
    ("chdir", 80),
    ("fchdir", 81),
    ("rename", 82),
    ("mkdir", 83),
    ("rmdir", 84),
    ("creat", 85),
    ("link", 86),
    ("unlink", 87),
    ("symlink", 88),
    ("readlink", 89),
    ("chmod", 90),
    ("fchmod", 91),
    ("chown", 92),
    ("fchown", 93),
    ("lchown", 94),
    ("umask", 95),
    ("gettimeofday", 96),
    ("getrlimit", 97),
    ("getrusage", 98),
    ("sysinfo", 99),
    ("times", 100),
    ("ptrace", 101),
    ("getuid", 102),
    ("syslog", 103),
    ("getgid", 104),
    ("setuid", 105),
    ("setgid", 106),
    ("geteuid", 107),
    ("getegid", 108),
    ("setpgid", 109),
    ("getppid", 110),
    ("getpgrp", 111),
    ("setsid", 112),
    ("setreuid", 113),
    ("setregid", 114),
    ("getgroups", 115),
    ("setgroups", 116),
    ("setresuid", 117),
    ("getresuid", 118),
    ("setresgid", 119),
    ("getresgid", 120),
    ("getpgid", 121),
    ("setfsuid", 122),
    ("setfsgid", 123),
    ("getsid", 124),
    ("capget", 125),
    ("capset", 126),
    ("rt_sigpending", 127),
    ("rt_sigtimedwait", 128),
    ("rt_sigqueueinfo", 129),
    ("rt_sigsuspend", 130),
    ("sigaltstack", 131),
    ("utime", 132),
    ("mknod", 133),
    ("uselib", 134),
    ("personality", 135),
    ("ustat", 136),
    ("statfs", 137),
    ("fstatfs", 138),
    ("sysfs", 139),
    ("getpriority", 140),
    ("setpriority", 141),
    ("sched_setparam", 142),
    ("sched_getparam", 143),
    ("sched_setscheduler", 144),
    ("sched_getscheduler", 145),
    ("sched_get_priority_max", 146),
    ("sched_get_priority_min", 147),
    ("sched_rr_get_interval", 148),
    ("mlock", 149),
    ("munlock", 150),
    ("mlockall", 151),
    ("munlockall", 152),
    ("vhangup", 153),
    ("modify_ldt", 154),
    ("pivot_root", 155),
    ("prctl", 157),
    ("arch_prctl", 158),
    ("adjtimex", 159),
    ("setrlimit", 160),
    ("chroot", 161),
    ("sync", 162),
    ("acct", 163),
    ("settimeofday", 164),
    ("mount", 165),
    ("umount2", 166),
    ("swapon", 167),
    ("swapoff", 168),
    ("reboot", 169),
    ("sethostname", 170),
    ("setdomainname", 171),
    ("iopl", 172),
    ("ioperm", 173),
    ("init_module", 175),
    ("delete_module", 176),
    ("quotactl", 179),
    ("gettid", 186),
    ("readahead", 187),
    ("setxattr", 188),
    ("lsetxattr", 189),
    ("fsetxattr", 190),
    ("getxattr", 191),
    ("lgetxattr", 192),
    ("fgetxattr", 193),
    ("listxattr", 194),
    ("llistxattr", 195),
    ("flistxattr", 196),
    ("removexattr", 197),
    ("lremovexattr", 198),
    ("fremovexattr", 199),
    ("tkill", 200),
    ("time", 201),
    ("futex", 202),
    ("sched_setaffinity", 203),
    ("sched_getaffinity", 204),
    ("io_setup", 206),
    ("io_destroy", 207),
    ("io_getevents", 208),
    ("io_submit", 209),
    ("io_cancel", 210),
    ("lookup_dcookie", 212),
    ("epoll_create", 213),
    ("remap_file_pages", 216),
    ("getdents64", 217),
    ("set_tid_address", 218),
    ("restart_syscall", 219),
    ("semtimedop", 220),
    ("fadvise64", 221),
    ("timer_create", 222),
    ("timer_settime", 223),
    ("timer_gettime", 224),
    ("timer_getoverrun", 225),
    ("timer_delete", 226),
    ("clock_settime", 227),
    ("clock_gettime", 228),
    ("clock_getres", 229),
    ("clock_nanosleep", 230),
    ("exit_group", 231),
    ("epoll_wait", 232),
    ("epoll_ctl", 233),
    ("tgkill", 234),
    ("utimes", 235),
    ("waitid", 247),
    ("add_key", 248),
    ("request_key", 249),
    ("keyctl", 250),
    ("openat", 257),
    ("mkdirat", 258),
    ("mknodat", 259),
    ("fchownat", 260),
    ("futimesat", 261),
    ("newfstatat", 262),
    ("unlinkat", 263),
    ("renameat", 264),
    ("linkat", 265),
    ("symlinkat", 266),
    ("readlinkat", 267),
    ("fchmodat", 268),
    ("faccessat", 269),
    ("pselect6", 270),
    ("ppoll", 271),
    ("unshare", 272),
    ("set_robust_list", 273),
    ("get_robust_list", 274),
    ("splice", 275),
    ("tee", 276),
    ("sync_file_range", 277),
    ("vmsplice", 278),
    ("move_pages", 279),
    ("utimensat", 280),
    ("epoll_pwait", 281),
    ("signalfd", 282),
    ("timerfd_create", 283),
    ("eventfd", 284),
    ("fallocate", 285),
    ("timerfd_settime", 286),
    ("timerfd_gettime", 287),
    ("accept4", 288),
    ("signalfd4", 289),
    ("eventfd2", 290),
    ("epoll_create1", 291),
    ("dup3", 292),
    ("pipe2", 293),
    ("inotify_init1", 294),
    ("preadv", 295),
    ("pwritev", 296),
    ("rt_tgsigqueueinfo", 297),
    ("perf_event_open", 298),
    ("recvmmsg", 299),
    ("fanotify_init", 300),
    ("fanotify_mark", 301),
    ("prlimit64", 302),
    ("name_to_handle_at", 303),
    ("open_by_handle_at", 304),
    ("clock_adjtime", 305),
    ("syncfs", 306),
    ("sendmmsg", 307),
    ("setns", 308),
    ("getcpu", 309),
    ("process_vm_readv", 310),
    ("process_vm_writev", 311),
    ("kcmp", 312),
    ("finit_module", 313),
    ("sched_setattr", 314),
    ("sched_getattr", 315),
    ("renameat2", 316),
    ("seccomp", 317),
    ("getrandom", 318),
    ("memfd_create", 319),
    ("kexec_file_load", 320),
    ("bpf", 321),
    ("execveat", 322),
    ("userfaultfd", 323),
    ("membarrier", 324),
    ("mlock2", 325),
    ("copy_file_range", 326),
    ("preadv2", 327),
    ("pwritev2", 328),
    ("pkey_mprotect", 329),
    ("pkey_alloc", 330),
    ("pkey_free", 331),
    ("statx", 332),
    ("io_pgetevents", 333),
    ("rseq", 334),
    ("pidfd_send_signal", 424),
    ("io_uring_setup", 425),
    ("io_uring_enter", 426),
    ("io_uring_register", 427),
    ("open_tree", 428),
    ("move_mount", 429),
    ("fsopen", 430),
    ("fsconfig", 431),
    ("fsmount", 432),
    ("fspick", 433),
    ("pidfd_open", 434),
    ("clone3", 435),
    ("close_range", 436),
    ("openat2", 437),
    ("pidfd_getfd", 438),
    ("faccessat2", 439),
    ("process_madvise", 440),
    ("epoll_pwait2", 441),
    ("mount_setattr", 442),
    ("quotactl_fd", 443),
    ("landlock_create_ruleset", 444),
    ("landlock_add_rule", 445),
    ("landlock_restrict_self", 446),
    ("memfd_secret", 447),
    ("process_mrelease", 448),
    ("futex_waitv", 449),
    ("set_mempolicy_home_node", 450),
    ("cachestat", 451),
    ("fchmodat2", 452),
    ("map_shadow_stack", 453),
    ("futex_wake", 454),
    ("futex_wait", 455),
    ("futex_requeue", 456),
    ("statmount", 457),
    ("listmount", 458),
    ("lsm_get_self_attr", 459),
    ("lsm_set_self_attr", 460),
    ("lsm_list_modules", 461),
    ("mseal", 462),
];

#[cfg(target_os = "linux")]
fn linux_lookup(name: &str) -> Option<i64> {
    // Defer to libc's SYS_* constants. We use a big match because the
    // constants are not enumerable at compile time.
    Some(match name {
        "read" => libc::SYS_read,
        "write" => libc::SYS_write,
        "open" => libc::SYS_open,
        "close" => libc::SYS_close,
        "stat" => libc::SYS_stat,
        "fstat" => libc::SYS_fstat,
        "lstat" => libc::SYS_lstat,
        "poll" => libc::SYS_poll,
        "lseek" => libc::SYS_lseek,
        "mmap" => libc::SYS_mmap,
        "mprotect" => libc::SYS_mprotect,
        "munmap" => libc::SYS_munmap,
        "brk" => libc::SYS_brk,
        "rt_sigaction" => libc::SYS_rt_sigaction,
        "rt_sigprocmask" => libc::SYS_rt_sigprocmask,
        "rt_sigreturn" => libc::SYS_rt_sigreturn,
        "ioctl" => libc::SYS_ioctl,
        "pread64" => libc::SYS_pread64,
        "pwrite64" => libc::SYS_pwrite64,
        "readv" => libc::SYS_readv,
        "writev" => libc::SYS_writev,
        "access" => libc::SYS_access,
        "pipe" => libc::SYS_pipe,
        "select" => libc::SYS_select,
        "sched_yield" => libc::SYS_sched_yield,
        "mremap" => libc::SYS_mremap,
        "msync" => libc::SYS_msync,
        "mincore" => libc::SYS_mincore,
        "madvise" => libc::SYS_madvise,
        "shmget" => libc::SYS_shmget,
        "shmat" => libc::SYS_shmat,
        "shmctl" => libc::SYS_shmctl,
        "dup" => libc::SYS_dup,
        "dup2" => libc::SYS_dup2,
        "pause" => libc::SYS_pause,
        "nanosleep" => libc::SYS_nanosleep,
        "getitimer" => libc::SYS_getitimer,
        "alarm" => libc::SYS_alarm,
        "setitimer" => libc::SYS_setitimer,
        "getpid" => libc::SYS_getpid,
        "sendfile" => libc::SYS_sendfile,
        "socket" => libc::SYS_socket,
        "connect" => libc::SYS_connect,
        "accept" => libc::SYS_accept,
        "sendto" => libc::SYS_sendto,
        "recvfrom" => libc::SYS_recvfrom,
        "sendmsg" => libc::SYS_sendmsg,
        "recvmsg" => libc::SYS_recvmsg,
        "shutdown" => libc::SYS_shutdown,
        "bind" => libc::SYS_bind,
        "listen" => libc::SYS_listen,
        "getsockname" => libc::SYS_getsockname,
        "getpeername" => libc::SYS_getpeername,
        "socketpair" => libc::SYS_socketpair,
        "setsockopt" => libc::SYS_setsockopt,
        "getsockopt" => libc::SYS_getsockopt,
        "clone" => libc::SYS_clone,
        "fork" => libc::SYS_fork,
        "vfork" => libc::SYS_vfork,
        "execve" => libc::SYS_execve,
        "exit" => libc::SYS_exit,
        "wait4" => libc::SYS_wait4,
        "kill" => libc::SYS_kill,
        "uname" => libc::SYS_uname,
        "semget" => libc::SYS_semget,
        "semop" => libc::SYS_semop,
        "semctl" => libc::SYS_semctl,
        "shmdt" => libc::SYS_shmdt,
        "msgget" => libc::SYS_msgget,
        "msgsnd" => libc::SYS_msgsnd,
        "msgrcv" => libc::SYS_msgrcv,
        "msgctl" => libc::SYS_msgctl,
        "fcntl" => libc::SYS_fcntl,
        "flock" => libc::SYS_flock,
        "fsync" => libc::SYS_fsync,
        "fdatasync" => libc::SYS_fdatasync,
        "truncate" => libc::SYS_truncate,
        "ftruncate" => libc::SYS_ftruncate,
        "getdents" => libc::SYS_getdents,
        "getcwd" => libc::SYS_getcwd,
        "chdir" => libc::SYS_chdir,
        "fchdir" => libc::SYS_fchdir,
        "rename" => libc::SYS_rename,
        "mkdir" => libc::SYS_mkdir,
        "rmdir" => libc::SYS_rmdir,
        "creat" => libc::SYS_creat,
        "link" => libc::SYS_link,
        "unlink" => libc::SYS_unlink,
        "symlink" => libc::SYS_symlink,
        "readlink" => libc::SYS_readlink,
        "chmod" => libc::SYS_chmod,
        "fchmod" => libc::SYS_fchmod,
        "chown" => libc::SYS_chown,
        "fchown" => libc::SYS_fchown,
        "lchown" => libc::SYS_lchown,
        "umask" => libc::SYS_umask,
        "gettimeofday" => libc::SYS_gettimeofday,
        "getrlimit" => libc::SYS_getrlimit,
        "getrusage" => libc::SYS_getrusage,
        "sysinfo" => libc::SYS_sysinfo,
        "times" => libc::SYS_times,
        "ptrace" => libc::SYS_ptrace,
        "getuid" => libc::SYS_getuid,
        "syslog" => libc::SYS_syslog,
        "getgid" => libc::SYS_getgid,
        "setuid" => libc::SYS_setuid,
        "setgid" => libc::SYS_setgid,
        "geteuid" => libc::SYS_geteuid,
        "getegid" => libc::SYS_getegid,
        "setpgid" => libc::SYS_setpgid,
        "getppid" => libc::SYS_getppid,
        "getpgrp" => libc::SYS_getpgrp,
        "setsid" => libc::SYS_setsid,
        "setreuid" => libc::SYS_setreuid,
        "setregid" => libc::SYS_setregid,
        "getgroups" => libc::SYS_getgroups,
        "setgroups" => libc::SYS_setgroups,
        "setresuid" => libc::SYS_setresuid,
        "getresuid" => libc::SYS_getresuid,
        "setresgid" => libc::SYS_setresgid,
        "getresgid" => libc::SYS_getresgid,
        "getpgid" => libc::SYS_getpgid,
        "setfsuid" => libc::SYS_setfsuid,
        "setfsgid" => libc::SYS_setfsgid,
        "getsid" => libc::SYS_getsid,
        "capget" => libc::SYS_capget,
        "capset" => libc::SYS_capset,
        "rt_sigpending" => libc::SYS_rt_sigpending,
        "rt_sigtimedwait" => libc::SYS_rt_sigtimedwait,
        "rt_sigqueueinfo" => libc::SYS_rt_sigqueueinfo,
        "rt_sigsuspend" => libc::SYS_rt_sigsuspend,
        "sigaltstack" => libc::SYS_sigaltstack,
        "utime" => libc::SYS_utime,
        "mknod" => libc::SYS_mknod,
        "uselib" => libc::SYS_uselib,
        "personality" => libc::SYS_personality,
        "ustat" => libc::SYS_ustat,
        "statfs" => libc::SYS_statfs,
        "fstatfs" => libc::SYS_fstatfs,
        "sysfs" => libc::SYS_sysfs,
        "getpriority" => libc::SYS_getpriority,
        "setpriority" => libc::SYS_setpriority,
        "sched_setparam" => libc::SYS_sched_setparam,
        "sched_getparam" => libc::SYS_sched_getparam,
        "sched_setscheduler" => libc::SYS_sched_setscheduler,
        "sched_getscheduler" => libc::SYS_sched_getscheduler,
        "sched_get_priority_max" => libc::SYS_sched_get_priority_max,
        "sched_get_priority_min" => libc::SYS_sched_get_priority_min,
        "sched_rr_get_interval" => libc::SYS_sched_rr_get_interval,
        "mlock" => libc::SYS_mlock,
        "munlock" => libc::SYS_munlock,
        "mlockall" => libc::SYS_mlockall,
        "munlockall" => libc::SYS_munlockall,
        "vhangup" => libc::SYS_vhangup,
        "modify_ldt" => libc::SYS_modify_ldt,
        "pivot_root" => libc::SYS_pivot_root,
        "prctl" => libc::SYS_prctl,
        "arch_prctl" => libc::SYS_arch_prctl,
        "adjtimex" => libc::SYS_adjtimex,
        "setrlimit" => libc::SYS_setrlimit,
        "chroot" => libc::SYS_chroot,
        "sync" => libc::SYS_sync,
        "acct" => libc::SYS_acct,
        "settimeofday" => libc::SYS_settimeofday,
        "mount" => libc::SYS_mount,
        "umount2" => libc::SYS_umount2,
        "swapon" => libc::SYS_swapon,
        "swapoff" => libc::SYS_swapoff,
        "reboot" => libc::SYS_reboot,
        "sethostname" => libc::SYS_sethostname,
        "setdomainname" => libc::SYS_setdomainname,
        "iopl" => libc::SYS_iopl,
        "ioperm" => libc::SYS_ioperm,
        "init_module" => libc::SYS_init_module,
        "delete_module" => libc::SYS_delete_module,
        "quotactl" => libc::SYS_quotactl,
        "gettid" => libc::SYS_gettid,
        "readahead" => libc::SYS_readahead,
        "setxattr" => libc::SYS_setxattr,
        "lsetxattr" => libc::SYS_lsetxattr,
        "fsetxattr" => libc::SYS_fsetxattr,
        "getxattr" => libc::SYS_getxattr,
        "lgetxattr" => libc::SYS_lgetxattr,
        "fgetxattr" => libc::SYS_fgetxattr,
        "listxattr" => libc::SYS_listxattr,
        "llistxattr" => libc::SYS_llistxattr,
        "flistxattr" => libc::SYS_flistxattr,
        "removexattr" => libc::SYS_removexattr,
        "lremovexattr" => libc::SYS_lremovexattr,
        "fremovexattr" => libc::SYS_fremovexattr,
        "tkill" => libc::SYS_tkill,
        "time" => libc::SYS_time,
        "futex" => libc::SYS_futex,
        "sched_setaffinity" => libc::SYS_sched_setaffinity,
        "sched_getaffinity" => libc::SYS_sched_getaffinity,
        "io_setup" => libc::SYS_io_setup,
        "io_destroy" => libc::SYS_io_destroy,
        "io_getevents" => libc::SYS_io_getevents,
        "io_submit" => libc::SYS_io_submit,
        "io_cancel" => libc::SYS_io_cancel,
        "epoll_create" => libc::SYS_epoll_create,
        "getdents64" => libc::SYS_getdents64,
        "set_tid_address" => libc::SYS_set_tid_address,
        "restart_syscall" => libc::SYS_restart_syscall,
        "semtimedop" => libc::SYS_semtimedop,
        "fadvise64" => libc::SYS_fadvise64,
        "timer_create" => libc::SYS_timer_create,
        "timer_settime" => libc::SYS_timer_settime,
        "timer_gettime" => libc::SYS_timer_gettime,
        "timer_getoverrun" => libc::SYS_timer_getoverrun,
        "timer_delete" => libc::SYS_timer_delete,
        "clock_settime" => libc::SYS_clock_settime,
        "clock_gettime" => libc::SYS_clock_gettime,
        "clock_getres" => libc::SYS_clock_getres,
        "clock_nanosleep" => libc::SYS_clock_nanosleep,
        "exit_group" => libc::SYS_exit_group,
        "epoll_wait" => libc::SYS_epoll_wait,
        "epoll_ctl" => libc::SYS_epoll_ctl,
        "tgkill" => libc::SYS_tgkill,
        "utimes" => libc::SYS_utimes,
        "waitid" => libc::SYS_waitid,
        "add_key" => libc::SYS_add_key,
        "request_key" => libc::SYS_request_key,
        "keyctl" => libc::SYS_keyctl,
        "openat" => libc::SYS_openat,
        "mkdirat" => libc::SYS_mkdirat,
        "mknodat" => libc::SYS_mknodat,
        "fchownat" => libc::SYS_fchownat,
        "futimesat" => libc::SYS_futimesat,
        "newfstatat" => libc::SYS_newfstatat,
        "unlinkat" => libc::SYS_unlinkat,
        "renameat" => libc::SYS_renameat,
        "linkat" => libc::SYS_linkat,
        "symlinkat" => libc::SYS_symlinkat,
        "readlinkat" => libc::SYS_readlinkat,
        "fchmodat" => libc::SYS_fchmodat,
        "faccessat" => libc::SYS_faccessat,
        "pselect6" => libc::SYS_pselect6,
        "ppoll" => libc::SYS_ppoll,
        "unshare" => libc::SYS_unshare,
        "set_robust_list" => libc::SYS_set_robust_list,
        "get_robust_list" => libc::SYS_get_robust_list,
        "splice" => libc::SYS_splice,
        "tee" => libc::SYS_tee,
        "sync_file_range" => libc::SYS_sync_file_range,
        "vmsplice" => libc::SYS_vmsplice,
        "move_pages" => libc::SYS_move_pages,
        "utimensat" => libc::SYS_utimensat,
        "epoll_pwait" => libc::SYS_epoll_pwait,
        "signalfd" => libc::SYS_signalfd,
        "timerfd_create" => libc::SYS_timerfd_create,
        "eventfd" => libc::SYS_eventfd,
        "fallocate" => libc::SYS_fallocate,
        "timerfd_settime" => libc::SYS_timerfd_settime,
        "timerfd_gettime" => libc::SYS_timerfd_gettime,
        "accept4" => libc::SYS_accept4,
        "signalfd4" => libc::SYS_signalfd4,
        "eventfd2" => libc::SYS_eventfd2,
        "epoll_create1" => libc::SYS_epoll_create1,
        "dup3" => libc::SYS_dup3,
        "pipe2" => libc::SYS_pipe2,
        "inotify_init1" => libc::SYS_inotify_init1,
        "preadv" => libc::SYS_preadv,
        "pwritev" => libc::SYS_pwritev,
        "rt_tgsigqueueinfo" => libc::SYS_rt_tgsigqueueinfo,
        "perf_event_open" => libc::SYS_perf_event_open,
        "recvmmsg" => libc::SYS_recvmmsg,
        "fanotify_init" => libc::SYS_fanotify_init,
        "fanotify_mark" => libc::SYS_fanotify_mark,
        "prlimit64" => libc::SYS_prlimit64,
        "name_to_handle_at" => libc::SYS_name_to_handle_at,
        "open_by_handle_at" => libc::SYS_open_by_handle_at,
        "clock_adjtime" => libc::SYS_clock_adjtime,
        "syncfs" => libc::SYS_syncfs,
        "sendmmsg" => libc::SYS_sendmmsg,
        "setns" => libc::SYS_setns,
        "getcpu" => libc::SYS_getcpu,
        "process_vm_readv" => libc::SYS_process_vm_readv,
        "process_vm_writev" => libc::SYS_process_vm_writev,
        "kcmp" => libc::SYS_kcmp,
        "finit_module" => libc::SYS_finit_module,
        "sched_setattr" => libc::SYS_sched_setattr,
        "sched_getattr" => libc::SYS_sched_getattr,
        "renameat2" => libc::SYS_renameat2,
        "seccomp" => libc::SYS_seccomp,
        "getrandom" => libc::SYS_getrandom,
        "memfd_create" => libc::SYS_memfd_create,
        "kexec_file_load" => libc::SYS_kexec_file_load,
        "bpf" => libc::SYS_bpf,
        "execveat" => libc::SYS_execveat,
        "userfaultfd" => libc::SYS_userfaultfd,
        "membarrier" => libc::SYS_membarrier,
        "mlock2" => libc::SYS_mlock2,
        "copy_file_range" => libc::SYS_copy_file_range,
        "preadv2" => libc::SYS_preadv2,
        "pwritev2" => libc::SYS_pwritev2,
        "pkey_mprotect" => libc::SYS_pkey_mprotect,
        "pkey_alloc" => libc::SYS_pkey_alloc,
        "pkey_free" => libc::SYS_pkey_free,
        "statx" => libc::SYS_statx,
        "io_pgetevents" => libc::SYS_io_pgetevents,
        "rseq" => libc::SYS_rseq,
        "pidfd_send_signal" => libc::SYS_pidfd_send_signal,
        "io_uring_setup" => libc::SYS_io_uring_setup,
        "io_uring_enter" => libc::SYS_io_uring_enter,
        "io_uring_register" => libc::SYS_io_uring_register,
        "open_tree" => libc::SYS_open_tree,
        "move_mount" => libc::SYS_move_mount,
        "fsopen" => libc::SYS_fsopen,
        "fsconfig" => libc::SYS_fsconfig,
        "fsmount" => libc::SYS_fsmount,
        "fspick" => libc::SYS_fspick,
        "pidfd_open" => libc::SYS_pidfd_open,
        "clone3" => libc::SYS_clone3,
        "close_range" => libc::SYS_close_range,
        "openat2" => libc::SYS_openat2,
        "pidfd_getfd" => libc::SYS_pidfd_getfd,
        "faccessat2" => libc::SYS_faccessat2,
        "process_madvise" => libc::SYS_process_madvise,
        "epoll_pwait2" => libc::SYS_epoll_pwait2,
        "mount_setattr" => libc::SYS_mount_setattr,
        "landlock_create_ruleset" => libc::SYS_landlock_create_ruleset,
        "landlock_add_rule" => libc::SYS_landlock_add_rule,
        "landlock_restrict_self" => libc::SYS_landlock_restrict_self,
        "memfd_secret" => libc::SYS_memfd_secret,
        "process_mrelease" => libc::SYS_process_mrelease,
        "futex_waitv" => libc::SYS_futex_waitv,
        "set_mempolicy_home_node" => libc::SYS_set_mempolicy_home_node,
        "cachestat" => libc::SYS_cachestat,
        "fchmodat2" => libc::SYS_fchmodat2,
        "map_shadow_stack" => libc::SYS_map_shadow_stack,
        "futex_wake" => libc::SYS_futex_wake,
        "futex_wait" => libc::SYS_futex_wait,
        "futex_requeue" => libc::SYS_futex_requeue,
        "statmount" => libc::SYS_statmount,
        "listmount" => libc::SYS_listmount,
        "lsm_get_self_attr" => libc::SYS_lsm_get_self_attr,
        "lsm_set_self_attr" => libc::SYS_lsm_set_self_attr,
        "lsm_list_modules" => libc::SYS_lsm_list_modules,
        "mseal" => libc::SYS_mseal,
        _ => return fallback_x86_64_lookup(name),
    } as i64)
}

/// Fallback lookup for syscalls that may not be defined in an older `libc`
/// crate on the target, or on non-Linux platforms.
fn fallback_x86_64_lookup(name: &str) -> Option<i64> {
    static TABLE: OnceLock<HashMap<&'static str, i64>> = OnceLock::new();
    let table = TABLE.get_or_init(|| {
        SYSCALL_NAMES.iter().copied().collect::<HashMap<_, _>>()
    });
    table.get(name).copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_syscalls_resolve() {
        assert_eq!(syscall_name_to_number("read"), Some(0));
        assert_eq!(syscall_name_to_number("write"), Some(1));
        assert_eq!(syscall_name_to_number("openat"), Some(257));
        assert_eq!(syscall_name_to_number("execve"), Some(59));
    }

    #[test]
    fn unknown_syscall_returns_none() {
        assert_eq!(syscall_name_to_number("not_a_syscall"), None);
    }

    #[test]
    fn table_is_unique() {
        let mut names: Vec<&str> = SYSCALL_NAMES.iter().map(|(n, _)| *n).collect();
        names.sort();
        let len_before = names.len();
        names.dedup();
        assert_eq!(names.len(), len_before, "duplicate syscall names in table");
    }
}
